services:
  spring-ai-mcp-example-note-mcp-host:
    build: ./note-mcp-host
    depends_on:
      spring-ai-mcp-example-ollama:
        condition: service_healthy
      spring-ai-mcp-example-note-mcp-server:
        condition: service_healthy
      spring-ai-mcp-example-wikipedia-mcp-server:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

  spring-ai-mcp-example-note-mcp-server:
    build: ./note-mcp-server
    depends_on:
      spring-ai-mcp-example-mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8081/actuator/health > /dev/null || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 5

  spring-ai-mcp-example-wikipedia-mcp-server:
    build: ./wikipedia-mcp-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8082/actuator/health > /dev/null || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 5

  spring-ai-mcp-example-ollama:
    image: ollama/ollama
    volumes:
      - spring-ai-mcp-example-ollama-volume:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              count: all
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 2s
      timeout: 10s
      retries: 5

  spring-ai-mcp-example-ollama-model-setup:
    image: ollama/ollama
    depends_on:
      spring-ai-mcp-example-ollama:
        condition: service_healthy
    entrypoint: >
      sh -c "ollama pull qwen3:4b"
    environment:
      OLLAMA_HOST: http://spring-ai-mcp-example-ollama:11434
    restart: no

  spring-ai-mcp-example-mysql:
    image: mysql:9
    volumes:
      - spring-ai-mcp-example-mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: note_mcp_server_db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h localhost -uroot -pchangeme note_mcp_server_db -e 'SELECT 1' > /dev/null || exit 1",
        ]
      interval: 1s
      timeout: 2s
      retries: 60
    restart: unless-stopped

volumes:
  spring-ai-mcp-example-ollama-volume:
  spring-ai-mcp-example-mysql-volume:
