spring:
  application:
    name: note-mcp-host

  ai:
    mcp:
      client:
        name: note-mcp-client
        version: 0.0.1
        streamable-http:
          connections:
            note-mcp-server:
              url: http://localhost:8081
            wikipedia-mcp-server:
              url: http://localhost:8082
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:4b

logging:
  level:
    org.springframework.ai: debug
    io.modelcontextprotocol: debug
